export enum FocusableInputs {
  ROUTE_PATH = 'ROUTE_PATH',
  ROUTE_FILTER = 'ROUTE_FILTER',
  DATABUCKET_NAME = 'DATABUCKET_NAME',
  DATABUCKET_FILTER = 'DATABUCKET_FILTER'
}

export enum DropActionType {
  BEFORE = 'BEFORE',
  INSIDE = 'INSIDE',
  AFTER = 'AFTER'
}
