export enum FocusableInputs {
  ENVIRONMENT_NAME = 'ENVIRONMENT_NAME',
  ROUTE_PATH = 'ROUTE_PATH',
  ROUTE_FILTER = 'ROUTE_FILTER',
  DATABUCKET_NAME = 'DATABUCKET_NAME',
  DATABUCKET_VALUE = 'DATABUCKET_VALUE',
  DATABUCKET_FILTER = 'DATABUCKET_FILTER'
}
