export enum FocusableInputs {
  ROUTE_PATH = 'ROUTE_PATH',
  ROUTE_FILTER = 'ROUTE_FILTER',
  DATABUCKET_NAME = 'DATABUCKET_NAME',
  DATABUCKET_FILTER = 'DATABUCKET_FILTER',
  TEMPLATES_FILTER = 'TEMPLATES_FILTER',
  COMMAND_PALETTE_SEARCH = 'COMMAND_PALETTE_SEARCH',
  CALLBACK_NAME = 'CALLBACK_NAME',
  CALLBACK_FILTER = 'CALLBACK_FILTER'
}
