export enum ServerErrorCodes {
  PORT_ALREADY_USED = 'PORT_ALREADY_USED',
  PORT_INVALID = 'PORT_INVALID',
  HOSTNAME_UNKNOWN = 'HOSTNAME_UNKNOWN',
  HOSTNAME_UNAVAILABLE = 'HOSTNAME_UNAVAILABLE',
  REQUEST_BODY_PARSE = 'REQUEST_BODY_PARSE',
  ROUTE_CREATION_ERROR = 'ROUTE_CREATION_ERROR',
  ROUTE_CREATION_ERROR_REGEX = 'ROUTE_CREATION_ERROR_REGEX',
  ROUTE_SERVING_ERROR = 'ROUTE_SERVING_ERROR',
  ROUTE_FILE_SERVING_ERROR = 'ROUTE_FILE_SERVING_ERROR',
  PROXY_ERROR = 'PROXY_ERROR',
  UNKNOWN_SERVER_ERROR = 'UNKNOWN_SERVER_ERROR',
  CERT_FILE_NOT_FOUND = 'CERT_FILE_NOT_FOUND',
  ROUTE_NO_LONGER_EXISTS = 'ROUTE_NO_LONGER_EXISTS',
  HEADER_PARSING_ERROR = 'HEADER_PARSING_ERROR',
  CALLBACK_ERROR = 'CALLBACK_ERROR',
  CALLBACK_FILE_ERROR = 'CALLBACK_FILE_ERROR',

  /**
   * Websocket related errors.
   */
  WS_UNKNOWN_ROUTE = 'WS_UNKNOWN_ROUTE',
  WS_UNSUPPORTED_CONTENT = 'WS_UNSUPPORTED_CONTENT',
  WS_SERVING_ERROR = 'WS_SERVING_ERROR'
}
