/* Contains faker helper function migration map for fakerjs migration from 7.6.1 to 8.1.0 */

export const FAKER_V7_TO_V8_MAPPING = {
  'name.firstName': 'person.firstName',
  'name.lastName': 'person.lastName',
  'name.middleName': 'person.middleName',
  'name.fullName': 'person.fullName',
  'name.gender': 'person.gender',
  'name.sex': 'person.sex',
  'name.sexType': 'person.sexType',
  'name.prefix': 'person.prefix',
  'name.suffix': 'person.suffix',
  'name.jobTitle': 'person.jobTitle',
  'name.jobDescriptor': 'person.jobDescriptor',
  'name.jobArea': 'person.jobArea',
  'name.jobType': 'person.jobType',
  'name.findName': 'person.fullName',
  'address.buildingNumber': 'location.buildingNumber',
  'address.cardinalDirection': 'location.cardinalDirection',
  'address.city': 'location.city',
  'address.cityName': 'location.city',
  'address.country': 'location.country',
  'address.countryCode': 'location.countryCode',
  'address.county': 'location.county',
  'address.direction': 'location.direction',
  'address.faker': 'location.faker',
  'address.latitude': 'location.latitude',
  'address.longitude': 'location.longitude',
  'address.nearbyGPSCoordinate': 'location.nearbyGPSCoordinate',
  'address.ordinalDirection': 'location.ordinalDirection',
  'address.secondaryAddress': 'location.secondaryAddress',
  'address.state': 'location.state',
  'address.stateAbbr': ['location.state', 'abbreviated=true'],
  'address.street': 'location.street',
  'address.streetAddress': 'location.streetAddress',
  'address.streetName': 'location.street',
  'address.timeZone': 'location.timeZone',
  'address.zipCode': 'location.zipCode',
  'address.zipCodeByState': 'location.zipCode',
  'address.cityPrefix': '',
  'address.citySuffix': '',
  'address.streetPrefix': '',
  'address.streetSuffix': '',
  'commerce.color': 'color.human',
  'company.companyName': 'company.name',
  'company.bs': 'company.buzzPhrase',
  'company.bsAdjective': 'company.buzzAdjective',
  'company.bsBuzz': 'company.buzzVerb',
  'company.bsNoun': 'company.buzzNoun',
  'company.companySuffix': 'company.name',
  'company.suffixes': 'company.name',
  'datatype.array': '',
  'datatype.bigInt': 'number.bigInt',
  'datatype.datetime': 'date.anytime',
  'datatype.float': 'number.float',
  'datatype.hexadecimal': 'number.hex',
  'datatype.json': '',
  'datatype.number': 'number.int',
  'datatype.string': 'string.sample',
  'datatype.uuid': 'string.uuid',
  fake: 'helper.fake',
  'finance.account': 'finance.accountNumber',
  'finance.masked': 'finance.maskedNumber',
  'git.shortSha': ['git.commitSha', 'length="7"'],
  'helpers.regexpStyleStringParse': 'helpers.fromRegExp',
  'helpers.repeatString': '',
  'image.abstract': ['image.urlLoremFlickr', 'category="abstract"'],
  'image.animals': ['image.urlLoremFlickr', 'category="animals"'],
  'image.business': ['image.urlLoremFlickr', 'category="business"'],
  'image.cats': ['image.urlLoremFlickr', 'category="cats"'],
  'image.city': ['image.urlLoremFlickr', 'category="city"'],
  'image.fashion': ['image.urlLoremFlickr', 'category="fashion"'],
  'image.food': ['image.urlLoremFlickr', 'category="food"'],
  'image.nature': ['image.urlLoremFlickr', 'category="nature"'],
  'image.nightlife': ['image.urlLoremFlickr', 'category="nightlife"'],
  'image.people': ['image.urlLoremFlickr', 'category="people"'],
  'image.sports': ['image.urlLoremFlickr', 'category="sports"'],
  'image.technics': ['image.urlLoremFlickr', 'category="technics"'],
  'image.transport': ['image.urlLoremFlickr', 'category="transport"'],
  'image.image': 'image.url',
  'image.imageUrl': 'image.url',
  'image.lorempixel': '',
  'mersenne.rand': '',
  'mersenne.seed': '',
  'mersenne.seed_array': '',
  'faker.phone.phoneNumber': 'phone.number',
  'faker.phone.phoneNumberFormat': '',
  'faker.phone.phoneFormats': '',
  'random.alpha': 'string.alpha',
  'random.alphaNumberic': 'string.alphanumeric',
  'random.numeric': 'string.numeric',
  'random.word': 'word.sample',
  'random.words': 'word.words'
};
