import {
  createLogger,
  format as logFormat,
  Logger,
  transports as logsTransports
} from 'winston';
import {
  ConsoleTransportInstance,
  FileTransportInstance,
  FileTransportOptions
} from 'winston/lib/winston/transports';

const autoGeneratedTokenMessagePatterns = [
  /(Admin API token \(auto-generated\):\s*)(.+)$/i
];

const redactAutoGeneratedTokenMessage = (value: string): string =>
  autoGeneratedTokenMessagePatterns.reduce(
    (redactedValue, pattern) => redactedValue.replace(pattern, '$1[REDACTED]'),
    value
  );

const fileTransportRedactionFormat = logFormat((info) => {
  if (typeof info.message === 'string') {
    info.message = redactAutoGeneratedTokenMessage(info.message);
  }

  return info;
});

export const createLoggerInstance = (
  fileTransportOptions?: FileTransportOptions | null
): Logger => {
  const transportsInstances: (
    | FileTransportInstance
    | ConsoleTransportInstance
  )[] = [
    new logsTransports.Console({
      handleExceptions: true,
      format: logFormat.combine(logFormat.timestamp(), logFormat.json())
    })
  ];

  if (fileTransportOptions) {
    transportsInstances.push(
      new logsTransports.File({
        ...fileTransportOptions,
        handleExceptions: true,
        format: logFormat.combine(
          fileTransportRedactionFormat(),
          logFormat.timestamp(),
          logFormat.json()
        )
      })
    );
  }

  return createLogger({
    level: 'info',
    transports: transportsInstances,
    exitOnError: false
  });
};
