module.exports = {
  externals: {
    "electron": "require('electron')",
    "child_process": "require('child_process')",
    "crypto": "require('crypto')",
    "events": "require('events')",
    "express": "require('express')",
    "http-proxy-middleware": "require('http-proxy-middleware')",
    "handlebars": "require('handlebars')",
    "fs": "require('fs')",
    "http": "require('http')",
    "https": "require('https')",
    "assert": "require('assert')",
    "dns": "require('dns')",
    "net": "require('net')",
    "os": "require('os')",
    "path": "require('path')",
    "querystring": "require('querystring')",
    "readline": "require('readline')",
    "repl": "require('repl')",
    "stream": "require('stream')",
    "string_decoder": "require('string_decoder')",
    "tls": "require('tls')",
    "url": "require('url')",
    "util": "require('util')",
    "zlib": "require('zlib')"
  },
};
