export enum Errors {
  JSON_PARSE = 'Error while parsing JSON during the call',
  INVALID_CONTENT_TYPE = 'Invalid Content-Type provided',
  FILE_NOT_EXISTS = 'This file cannot be served because it does not exists',
  FILE_TYPE_NOT_SUPPORTED = 'This type of file is not supported',
  PORT_INVALID = 'This port is invalid',
  PORT_ALREADY_USED = 'Port is already in use',
  EXPORT_ERROR = 'An error occured while exporting the file',
  EXPORT_ENVIRONMENT_CLIPBOARD_ERROR = 'An error occured while exporting the environment to the clipboard',
  EXPORT_ROUTE_CLIPBOARD_ERROR = 'An error occured while exporting the route to the clipboard',
  IMPORT_ERROR = 'An error occured while importing the file',
  IMPORT_FILE_WRONG_CHECKSUM = 'File content has an incorrect format and cannot be imported',
  IMPORT_CLIPBOARD_WRONG_CHECKSUM = 'Clipboard content has an incorrect format and cannot be imported',
  IMPORT_ENVIRONMENT_CLIPBOARD_ERROR = 'An error occured while importing the environment from the clipboard',
  IMPORT_ROUTE_CLIPBOARD_ERROR = 'An error occured while importing the route from the clipboard',
}
