import { FakerAvailableLocales } from 'src/app/models/faker.model';

export const FakerLocales: { code: FakerAvailableLocales; label: string }[] = [
  { code: 'ar', label: 'Arabic' },
  { code: 'az', label: 'Azerbaijani' },
  { code: 'zh_CN', label: 'Chinese' },
  { code: 'zh_TW', label: 'Chinese (Taiwan)' },
  { code: 'cz', label: 'Czech' },
  { code: 'nl', label: 'Dutch' },
  { code: 'nl_BE', label: 'Dutch (Belgium)' },
  { code: 'de', label: 'German' },
  { code: 'de_AT', label: 'German (Austria)' },
  { code: 'de_CH', label: 'German (Switzerland)' },
  { code: 'en', label: 'English' },
  { code: 'en_AU', label: 'Australia (English)' },
  { code: 'en_au_ocker', label: 'Australia Ocker (English)' },
  { code: 'en_BORK', label: 'Bork (English)' },
  { code: 'en_CA', label: 'Canada (English)' },
  { code: 'en_GB', label: 'Great Britain (English)' },
  { code: 'en_IE', label: 'Ireland (English)' },
  { code: 'en_IND', label: 'India (English)' },
  { code: 'en_ZA', label: 'South Africa (English)' },
  { code: 'en_US', label: 'United States (English)' },
  { code: 'es', label: 'Spanish' },
  { code: 'es_MX', label: 'Spanish Mexico' },
  { code: 'fa', label: 'Farsi' },
  { code: 'fr', label: 'French' },
  { code: 'fr_CA', label: 'French (Canada)' },
  { code: 'fr_CH', label: 'French (Switzerland)' },
  { code: 'ge', label: 'Georgian' },
  { code: 'it', label: 'Italian' },
  { code: 'id_ID', label: 'Indonesia' },
  { code: 'ja', label: 'Japanese' },
  { code: 'ko', label: 'Korean' },
  { code: 'nep', label: 'Nepalese' },
  { code: 'nb_NO', label: 'Norwegian' },
  { code: 'pl', label: 'Polish' },
  { code: 'pt_BR', label: 'Portuguese (Brazil)' },
  { code: 'pt_PT', label: 'Portuguese (Portugal)' },
  { code: 'ro', label: 'Romanian' },
  { code: 'ru', label: 'Russian' },
  { code: 'sk', label: 'Slovakian' },
  { code: 'sv', label: 'Swedish' },
  { code: 'tr', label: 'Turkish' },
  { code: 'uk', label: 'Ukrainian' },
  { code: 'vi', label: 'Vietnamese' }
];
