name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint and format
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint and check format
        run: |
          npm run lint
          npm run format

  test-libs:
    name: Libs - Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    needs: lint

    strategy:
      matrix:
        node: [18, 20, 22, 24, 26]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build and test
        run: |
          npm run build:libs
          npm run test:libs

  test-serverless:
    name: Serverless - Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    needs: [lint, test-libs]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build and test
        run: |
          npm run build:libs
          npm run build:serverless
          npm run test:serverless

  test-cli:
    name: CLI - Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    needs: [lint, test-libs]

    strategy:
      matrix:
        node: [18, 20, 22, 24, 26]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build and test
        run: |
          npm run build:libs
          npm run build:cli
          npm run test:cli

  test-desktop-packaged-win:
    name: Desktop packaged Windows - Build and test (${{ matrix.shard }}/4)
    runs-on: windows-latest
    timeout-minutes: 30

    needs: [lint, test-libs]

    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.15.0" # wait for https://github.com/electron/electron/issues/51619 to be fixed
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build:libs
          npm run build:desktop:ci
          npm run package:desktop:test:win
      - name: Run tests
        run: |
          npm run test:desktop:win -- -- --shard=${{ matrix.shard }}/4

  test-desktop-packaged-mac:
    name: Desktop packaged MacOS - Build and test (${{ matrix.shard }}/4)
    runs-on: macos-latest
    timeout-minutes: 30

    needs: [lint, test-libs]

    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]

    env:
      USE_HARD_LINKS: false

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.15.0" # wait for https://github.com/electron/electron/issues/51619 to be fixed
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build:libs
          npm run build:desktop:ci
          npm run package:desktop:test:mac
      - name: Run tests
        run: |
          npm run test:desktop:mac -- -- --shard=${{ matrix.shard }}/4

  test-desktop-packaged-linux:
    name: Desktop packaged Linux - Build and test (${{ matrix.shard }}/4)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    needs: [lint, test-libs]

    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]

    env:
      USE_HARD_LINKS: false

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.15.0" # wait for https://github.com/electron/electron/issues/51619 to be fixed
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build:libs
          npm run build:desktop:ci
          npm run package:desktop:test:linux
      - name: Run tests
        run: |
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          npm run test:desktop:linux -- -- --shard=${{ matrix.shard }}/4
