name: Release web app

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    tags:
      - web-v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"
          cache: npm
      - name: Install firebase
        run: npm install -g firebase-tools
      - name: Extract web app version
        id: web-version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/web-v* ]]; then
            WEB_VERSION=${GITHUB_REF#refs/tags/web-v}
          else
            WEB_VERSION=$(node -p -e "require('./packages/app/package.json').version")
          fi

          echo "WEB_VERSION=$WEB_VERSION" >> $GITHUB_OUTPUT
      - name: Build application
        run: |
          npm ci
          npm run build:libs
          npm run build:web:prod
      - name: Package web app artifact
        run: |
          mkdir -p release-assets
          cd packages/app/dist
          zip -r ../../../../release-assets/mockoon-web-app-v${{steps.web-version.outputs.WEB_VERSION}}.zip renderer
          cd ../../..
          sha256sum release-assets/mockoon-web-app-v${{steps.web-version.outputs.WEB_VERSION}}.zip > release-assets/mockoon-web-app-v${{steps.web-version.outputs.WEB_VERSION}}.sha256
      - name: Upload web app artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: web-app-dist-v${{steps.web-version.outputs.WEB_VERSION}}
          path: release-assets/
      - name: deploy
        run: |
          npm run deploy:web
